server:
  port: 8764
spring:
  application:
    name: gateway-sample
  cloud:
    nacos:
      username: nacos
      password: 7fDJZBbiLzO2
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
    gateway:
      server:
        webflux:
          routes:
            - id: consumer-reactive-sample
              uri: lb://consumer-reactive-sample
              predicates:
                - name: Path
                  args:
                    pattern: /consumer-reactive-sample/**
              filters:
                - StripPrefix=1
            - id: consumer-sample
              uri: lb://consumer-sample
              predicates:
                - name: Path
                  args:
                    pattern: /consumer-sample/**
              filters:
                - StripPrefix=1
            - id: provider-dubbo-sample
              uri: lb://provider-dubbo-sample
              predicates:
                - name: Path
                  args:
                    pattern: /provider-dubbo-sample/**
              filters:
                - StripPrefix=1

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info
