server:
  port: 8764
spring:
  application:
    name: gateway-sample
  cloud:
    nacos:
      username: nacos
      password: 7fDJZBbiLzO2
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
    gateway:
      server:
        webflux:
          routes:
            - id: consumer-reactive-sample
              uri: lb://consumer-reactive-sample
              predicates:
                - name: Path
                  args:
                    pattern: /consumer-reactive-sample/**
              filters:
                - StripPrefix=1
            - id: consumer-sample
              uri: lb://consumer-sample
              predicates:
                - name: Path
                  args:
                    pattern: /consumer-sample/**
              filters:
                - StripPrefix=1
            - id: provider-dubbo-sample
              uri: lb://provider-dubbo-sample
              predicates:
                - name: Path
                  args:
                    pattern: /provider-dubbo-sample/**
              filters:
                - StripPrefix=1
    sentinel:
      transport:
        dashboard: localhost:8081
      eager: true
      filter:
        enabled: true
      scg:
        order: -100
        fallback:
          mode: response
          response-status: 444
          response-body: '{"code":444,"msg":"Sentinel gateway block"}'
      datasource:
        ds1:
          nacos:
            server-addr: 127.0.0.1:8848
            username: nacos
            password: 7fDJZBbiLzO2
            group-id: SENTINEL_GROUP
            data-id: cloud.sample.gateway.gw-api-group
            data-type: json
            rule-type: gw-api-group
        ds2:
          nacos:
            server-addr: 127.0.0.1:8848
            username: nacos
            password: 7fDJZBbiLzO2
            group-id: SENTINEL_GROUP
            data-id: cloud.sample.gateway.gw-flow
            data-type: json
            rule-type: gw-flow

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info
