spring:
  application:
    name: stream-sample
  cloud:
    stream:
      function:
        definition: input
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        input-in-0:
          destination: stream-demo-topic
          group: stream-demo-consumer-group
        output-out-0:
          destination: stream-demo-topic
