server:
  port: 8766
spring:
  application:
    name: consumer-sample
  cloud:
    nacos:
      username: nacos
      password: 7fDJZBbiLzO2
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
    sentinel:
      transport:
        dashboard: localhost:8081
      eager: true
      datasource:
        ds1:
          nacos:
            server-addr: 127.0.0.1:8848
            username: nacos
            password: 7fDJZBbiLzO2
            group-id: SENTINEL_GROUP
            data-id: cloud.sample.consumer.flow
            data-type: json
            rule-type: flow
        ds2:
          nacos:
            server-addr: 127.0.0.1:8848
            username: nacos
            password: 7fDJZBbiLzO2
            group-id: SENTINEL_GROUP
            data-id: cloud.sample.consumer.degrade
            data-type: json
            rule-type: degrade

feign:
  sentinel:
    enabled: true

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info

dubbo:
  application:
    name: ${spring.application.name}
    qos-port: 33333
  protocol:
    name: tri
    port: -1
  registry:
    id: nacos-registry
    address: nacos://127.0.0.1:8848
    parameters:
      group: DEFAULT_GROUP
      username: nacos
      password: 7fDJZBbiLzO2
  tracing:
    enabled: true

