spring:
  application:
    name: provider-dubbo-sample

dubbo:
  application:
    name: ${spring.application.name}
    qos-port: 22222
  protocol:
    name: tri
    port: -1
  registry:
    id: nacos-registry
    address: nacos://127.0.0.1:8848
    parameters:
      group: DEFAULT_GROUP
      username: nacos
      password: 7fDJZBbiLzO2

